### PR TITLE
Make use of HTTP Response in WebHook

### PR DESCRIPTION
**Pull request by zubairov**

### CODE REVIEW

**Comment by zubairov** [comment]
@drobiazko I guess that should help to consumer what's coming out of WebHook action? What do you think?

**Comment by drobiazko** [comment]
@zubairov I think it will. However with the new step-by-step execution feature this might become obsolete very soon.

**Comment by zubairov** [comment]
Good, do you think that for the time being it would make sense to merge this PR?

**Comment by drobiazko** [comment]
yes, of course

**Pull request merged**
